name: Test

on:
  push:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '^1.21'

      - name: Test utilities
        run: go test -cover ./utils

      - name: Test solutions
        if: ${{ github.repository != 'devries/aoc_template' }}
        run: go test -cover ./day*